# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Website name
title: Eugen Dolezal
# Website URL
baseURL: 'https://eugendolezal.eu/'

############################
## LANGUAGE
############################

defaultContentLanguage: de
hasCJKLanguage: false
defaultContentLanguageInSubdir: true
removePathAccents: true

de:
  languageCode: de
  weight: 1
  contentDir: content/de
  title: Eugen Dolezal | Sozialethiker und Theologe
  params:
    description: Persönliche Website von Eugen R. Dolezal
  menu:
    main:
      - name: Über mich
        url: '#about'
        weight: 1

 en:
  languageCode: en-us
  weight: 2
  contentDir: content/en
  title: Eugen Dolezal | Ethicist and Theologian
  params:
    description: "Personal Website of Eugen R. Dolezal."
  menu:
    main:
      - name: About
        url: '#about'
        weight: 1
        
############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 80
  anchor: smart
timeout: 600000
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep
